# Site settings
title: Jiayi's Blog
SEOTitle: 加一的博客
header-img: img/ying.jpg
email: lijiayi19971127@hotmail.com
description: "Always"
keyword: "加一的博客, FPGA, STM32"
url: "http://SHIELDJY.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/SHIELDJY/SHIELDJY.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "A pessimist sees the difficulty in every opportunity; an optimist
sees the opportunity in every difficulty."
sidebar-avatar: /img/lijiayi_pic.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
github_username:    SHIELDJY
#facebook_username:  baiying.qiu.7
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 751d47451b1158f13b95                            #生成的clientID
  clientSecret: dc0a758dafb65a614975f4b6ae2d352269fb62bf    #生成的clientSecret
  repo: shieldjy.github.io    #仓库名称
  owner: SHIELDJY    #github用户名
  admin: SHIELDJY
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 955f8eaf34f8075f88178e36faa1f393

# Google Analytics
ga_track_id: 'UA-162295889-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "yuxi",
        href: "http://yuxiiii.github.io"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
